name: Main workflow
on: [push, pull_request]

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: npm install

      - name: Lint
        run: npm run format-check

      - name: Test
        run: npm test

    release:
      needs: run
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
      - name: Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
